# Generated by Django 5.2.1 on 2025-05-16 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ditina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imya', models.CharField(max_length=100, verbose_name="Ім'я")),
                ('prizvische', models.CharField(max_length=100, verbose_name='Прізвище')),
                ('region', models.CharField(choices=[('KYIV', 'Київ'), ('LVIV', 'Львів'), ('ODS', 'Одеса'), ('KHR', 'Харків'), ('DNI', 'Дніпро')], max_length=4, verbose_name='Регіон')),
                ('vik', models.PositiveIntegerField(verbose_name='Вік')),
                ('zrist', models.PositiveIntegerField(verbose_name='Зріст (у см)')),
                ('pryimaie_gormony', models.BooleanField(default=False, verbose_name='Приймає гормони')),
                ('data_stvorennia', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('data_onovlennia', models.DateTimeField(auto_now=True, verbose_name='Дата оновлення')),
            ],
            options={
                'verbose_name': 'Дитина',
                'verbose_name_plural': 'Діти',
                'ordering': ['prizvische', 'imya'],
            },
        ),
    ]
